"""CLI: init / connect / serve / sleep-now / stats / viewer."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Annotated


def _ensure_utf8_console() -> None:
    """Stop Windows cp1252 from crashing prints that contain →, ·, — etc.

    Python on Windows defaults sys.stdout/stderr to the legacy ANSI code page,
    so rich.Console emits Unicode that raises UnicodeEncodeError on the
    *last* print of an otherwise-successful CLI run. Reconfigure both streams
    to UTF-8 with 'replace' so a missing glyph degrades to '?' instead of
    aborting the process.
    """
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            try:
                stream.reconfigure(encoding="utf-8", errors="replace")
            except (OSError, ValueError):
                pass


_ensure_utf8_console()

import typer
from platformdirs import user_data_dir
from rich.console import Console
from rich.table import Table

from sincron_brain import storage
from sincron_brain.config import (
    DOTENV_FILENAME,
    LLM_API_KEY_ENV,
    LLM_PROVIDER_ENV,
    PROVIDER_API_KEY_ENV,
    PROVIDER_DEFAULT_MODEL,
    JudgeConfig,
    VaultConfig,
    load_config,
)
from sincron_brain.major_tags import DEFAULT_MAJOR_TAG_NAMES, default_major_tag_names_csv

JUDGE_PROVIDER_OVERRIDE_ENV = "SINCRON_BRAIN_JUDGE_PROVIDER"
JUDGE_MODEL_OVERRIDE_ENV = "SINCRON_BRAIN_JUDGE_MODEL"

app = typer.Typer(
    name="sincron-brain",
    help="Plug-and-play memory layer for AI agents. MCP server.",
    no_args_is_help=True,
)
console = Console(soft_wrap=True, emoji=False)


def _default_vault_path() -> Path:
    return Path(user_data_dir("sincron-brain", "sincron")) / "memory"


def _print_default_major_tags() -> None:
    """Show the canonical taxonomy so users see what's armed in a fresh vault."""
    console.print()
    console.print(f"[bold]Major Tags loaded:[/] {len(DEFAULT_MAJOR_TAG_NAMES)}")
    console.print(f"  {', '.join(DEFAULT_MAJOR_TAG_NAMES)}")


DOTENV_TEMPLATE = """# Sincron Brain judge credentials.
# Lines starting with # are comments. Shell-set env vars always win over this file.
#
# Pick ONE of the two paths below and uncomment it:
#
# ---- Generic path (recommended) ----
# LLM_API_KEY=sk-ant-...          # prefix identifies Anthropic / OpenAI / Gemini / Bedrock
# LLM_PROVIDER=anthropic          # only required for opaque keys
#                                 # (mistral / cohere / voyage / azure / ollama / custom)
#
# ---- Provider-specific path ----
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...
# GEMINI_API_KEY=AIza...
# MISTRAL_API_KEY=...
# (etc — see install docs)
"""

VAULT_GITIGNORE_BODY = """# Generated by sincron-brain connect. Adjust if you want to share parts of the vault.
.env
_index.sqlite
_audit.jsonl
_viewer.html
_draft/
_reactivation/
"""


def _write_env_template_if_missing(config: VaultConfig) -> Path:
    """Drop a .env template the first time a vault is connected, never overwrite."""
    dotenv_path = config.vault_path / DOTENV_FILENAME
    if dotenv_path.exists():
        return dotenv_path
    dotenv_path.write_text(DOTENV_TEMPLATE, encoding="utf-8")
    try:
        from sincron_brain import storage

        storage._restrict_owner_access(dotenv_path)
    except (OSError, AttributeError):
        pass
    return dotenv_path


def _write_vault_gitignore(config: VaultConfig) -> Path:
    """Make sure the vault's .gitignore protects secrets and rebuildable artifacts."""
    gi_path = config.vault_path / ".gitignore"
    if not gi_path.exists():
        gi_path.write_text(VAULT_GITIGNORE_BODY, encoding="utf-8")
    return gi_path


def _write_initial_viewer(config: VaultConfig) -> Path:
    """Generate the viewer right after connect so the user sees the taxonomy.

    The server's auto-refresh only kicks in when _viewer.html already exists,
    so writing it here is what turns "viewer reflects current state" into the
    default for every project — no manual `sincron-brain viewer` required.
    """
    from sincron_brain.viewer import write_viewer

    return write_viewer(config)


def _print_judge_status(config: VaultConfig) -> None:
    """Surface whether the sleep judge can actually run, or will fall back."""
    from sincron_brain import judge

    status = judge.judge_status(config)
    console.print()
    if status["ready"]:
        key_label = status.get("api_key_source") or status["api_key_env"]
        console.print(
            f"[bold]Judge:[/] [green]ready[/] · "
            f"{status['provider']}/{status['model']} · "
            f"key {key_label} detected"
        )
        console.print(
            "  To switch judge: [bold]sincron-brain set-judge --provider <name>[/] "
            f"(or set {JUDGE_PROVIDER_OVERRIDE_ENV} before `connect`)."
        )
    else:
        any_other_key = _detect_provider_from_env() is not None
        console.print(
            "[bold]Judge:[/] [yellow]FALLBACK MODE[/] · no provider API key detected in this shell."
        )
        console.print(
            "[yellow]  While in fallback, sleep indexes drafts mechanically:[/]"
        )
        console.print(
            "[yellow]    Major Tags collapse to `_uncategorized`, synopses are not "
            "rewritten, no go_deeper links are proposed.[/]"
        )
        dotenv_path = config.vault_path / DOTENV_FILENAME
        console.print("[yellow]  To enable cognitive indexing, do ONE of:[/]")
        console.print(
            f"[yellow]    A) Edit the vault .env (recommended — persists across shells):[/]"
        )
        console.print(f"         {dotenv_path}")
        console.print(
            f"       Uncomment the {LLM_API_KEY_ENV} line and paste your key. "
            "The provider is detected from the key prefix "
            "(sk-ant-* -> Anthropic, sk-* -> OpenAI, AIza* -> Gemini, "
            f"AKIA*/ASIA* -> Bedrock). For other providers, also uncomment {LLM_PROVIDER_ENV}."
        )
        console.print(
            f"[yellow]    B) Export the env var in the shell that starts the MCP client:[/]"
        )
        console.print(f'         $env:{LLM_API_KEY_ENV} = "<your-key>"')
        console.print(
            "[yellow]    After either path, run:[/] sincron-brain set-judge --auto  "
            "[yellow](confirms the provider)[/]"
        )


def _detect_provider_from_key(key: str) -> str | None:
    """Best-effort detection of the provider from the API key's known prefix.

    Returns None for providers whose keys don't carry a distinguishable shape
    (Mistral, Cohere, Voyage, Azure, Ollama, custom) — for those the user
    must also export LLM_PROVIDER or rely on the provider-specific env var.
    """
    key = key.strip()
    if not key:
        return None
    if key.startswith("sk-ant-"):
        return "anthropic"
    if key.startswith(("sk-proj-", "sk-svcacct-")):
        return "openai"
    if key.startswith("sk-"):
        return "openai"
    if key.startswith("AIza"):
        return "google"
    if key.startswith(("AKIA", "ASIA")):
        return "bedrock"
    return None


def _detect_provider_from_env() -> str | None:
    """Pick a provider from the env.

    Priority:
      1. LLM_PROVIDER (paired with LLM_API_KEY) — explicit canonical path.
      2. LLM_API_KEY whose prefix uniquely identifies a provider.
      3. First supported provider whose specific env var is set (legacy).
    """
    canonical_key = os.environ.get(LLM_API_KEY_ENV, "")
    canonical_provider = os.environ.get(LLM_PROVIDER_ENV, "").strip().lower()
    if canonical_provider in PROVIDER_API_KEY_ENV and canonical_key:
        return canonical_provider
    if canonical_key:
        sniffed = _detect_provider_from_key(canonical_key)
        if sniffed is not None:
            return sniffed
    for provider, env_var in PROVIDER_API_KEY_ENV.items():
        if os.environ.get(env_var):
            return provider
    return None


def _judge_provider_override() -> str | None:
    """Explicit override that beats both --provider flag detection and env-key detection."""
    value = os.environ.get(JUDGE_PROVIDER_OVERRIDE_ENV, "").strip().lower()
    if not value:
        return None
    if value not in PROVIDER_API_KEY_ENV:
        console.print(
            f"[yellow]Ignoring {JUDGE_PROVIDER_OVERRIDE_ENV}={value!r}[/] — "
            f"not a supported provider ({', '.join(PROVIDER_API_KEY_ENV)})."
        )
        return None
    return value


def _judge_model_override() -> str | None:
    value = os.environ.get(JUDGE_MODEL_OVERRIDE_ENV, "").strip()
    return value or None


def _describe_detection_source(provider: str) -> str:
    """Explain in plain words which env var caused the detection — used in connect output."""
    canonical_key = os.environ.get(LLM_API_KEY_ENV, "")
    canonical_provider = os.environ.get(LLM_PROVIDER_ENV, "").strip().lower()
    if canonical_key and canonical_provider == provider:
        return f"{LLM_API_KEY_ENV} + {LLM_PROVIDER_ENV}={provider}"
    if canonical_key and _detect_provider_from_key(canonical_key) == provider:
        return f"{LLM_API_KEY_ENV} (looks like {provider} key)"
    return f"{PROVIDER_API_KEY_ENV[provider]} in the environment"


def _apply_judge_config(config: VaultConfig, provider: str, model: str | None = None) -> None:
    """Mutate config.judge to point at a new provider/model and persist it to disk."""
    config.judge.provider = provider
    config.judge.model = model or PROVIDER_DEFAULT_MODEL[provider]
    config.judge.api_key_env = PROVIDER_API_KEY_ENV[provider]
    config.save()


def _create_vault(
    vault_path: Path,
    provider: str | None,
    yes: bool,
) -> VaultConfig:
    console.print(f"[bold]Creating vault at:[/] {vault_path}")

    override = _judge_provider_override()
    detected = _detect_provider_from_env()
    if provider:
        chosen_provider = provider
    elif override:
        chosen_provider = override
        console.print(
            f"[green]Using[/] [bold]{override}[/] from {JUDGE_PROVIDER_OVERRIDE_ENV} override."
        )
    elif detected:
        chosen_provider = detected
        source = _describe_detection_source(detected)
        console.print(
            f"[green]Detected[/] {source} — using [bold]{detected}[/] as the judge provider."
        )
    elif yes:
        chosen_provider = next(iter(PROVIDER_API_KEY_ENV))
        console.print(
            "[yellow]No provider API key detected in the environment.[/] "
            "Vault will be created with a placeholder judge config — see the "
            "Judge section below for how to point it at a real provider."
        )
    else:
        chosen_provider = _prompt_provider()

    api_key_env = PROVIDER_API_KEY_ENV[chosen_provider]
    model = _judge_model_override() or PROVIDER_DEFAULT_MODEL[chosen_provider]

    if not yes and not os.environ.get(api_key_env):
        console.print(
            f"[yellow]Warning:[/] {api_key_env} not set in environment. "
            f"Set it before running sleep_now()."
        )

    config = VaultConfig(
        vault_path=vault_path,
        judge=JudgeConfig(
            provider=chosen_provider,
            model=model,
            api_key_env=api_key_env,
        ),
    )
    storage.ensure_vault(config)
    with storage.open_db(config):
        pass
    config.save()
    return config


@app.command()
def init(
    path: Annotated[
        Path | None, typer.Option("--path", help="Vault directory. Default: user data dir.")
    ] = None,
    provider: Annotated[
        str | None, typer.Option("--provider", help="LLM judge provider (anthropic, openai, ...).")
    ] = None,
    yes: Annotated[
        bool, typer.Option("--yes", "-y", help="Skip prompts, use defaults.")
    ] = False,
) -> None:
    """Create a new memory vault."""
    vault_path = path or _default_vault_path()
    vault_path = vault_path.expanduser().resolve()

    if (vault_path / "_config.toml").exists():
        console.print(f"[yellow]Vault already exists at {vault_path}[/]")
        raise typer.Exit(1)

    config = _create_vault(vault_path, provider, yes)

    console.print("[green]Vault created.[/]")
    console.print(f"  Config: {config.config_file}")
    console.print(f"  Index:  {config.index_db}")
    console.print(f"  Judge:  {config.judge.provider} / {config.judge.model}")
    _print_default_major_tags()
    _print_judge_status(config)
    console.print()
    console.print("[bold]Connect a project to this vault:[/]")
    console.print(f'  sincron-brain connect --path "{vault_path}"')


@app.command()
def connect(
    path: Annotated[
        Path | None,
        typer.Option("--path", help="Vault directory. Default: <project>/memory."),
    ] = None,
    project: Annotated[
        Path, typer.Option("--project", help="Project directory where .mcp.json will be written.")
    ] = Path("."),
    provider: Annotated[
        str | None, typer.Option("--provider", help="LLM judge provider if a vault is created.")
    ] = None,
    yes: Annotated[
        bool, typer.Option("--yes", "-y", help="Skip prompts, use defaults if a vault is created.")
    ] = True,
) -> None:
    """Create/use a vault and write .mcp.json for the current project."""
    project_path = project.expanduser().resolve()

    if not project_path.exists():
        console.print(f"[red]Project directory not found:[/] {project_path}")
        raise typer.Exit(1)

    vault_path = (path if path is not None else project_path / "memory").expanduser().resolve()

    if (vault_path / "_config.toml").exists():
        config = load_config(vault_path)
        console.print(f"[green]Using existing vault:[/] {config.vault_path}")
        if provider:
            _apply_judge_config(config, provider)
            console.print(
                f"[green]Judge updated:[/] {config.judge.provider}/{config.judge.model}"
            )
    else:
        config = _create_vault(vault_path, provider, yes)
        console.print("[green]Vault created.[/]")

    mcp_file = _write_project_mcp_config(project_path, config)
    claude_settings = _sync_claude_project_settings(project_path)
    instruction_files = _sync_agent_instruction_files(project_path)
    viewer_path = _write_initial_viewer(config)
    env_file = _write_env_template_if_missing(config)
    gitignore_file = _write_vault_gitignore(config)
    console.print(f"[green]MCP config written:[/] {mcp_file}")
    console.print(f"[green]Claude project settings synced:[/] {claude_settings}")
    for instruction_file in instruction_files:
        console.print(f"[green]Agent instructions synced:[/] {instruction_file}")
    console.print(f"[green]Viewer ready:[/] {viewer_path}")
    console.print(f"[green]Env template:[/] {env_file}  [dim](edit to add LLM_API_KEY)[/]")
    console.print(f"[green]Vault .gitignore:[/] {gitignore_file}")
    _print_default_major_tags()
    _print_judge_status(config)
    console.print()
    console.print("[bold]Next steps:[/]")
    console.print("  1. Restart your MCP client/agent.")
    console.print("  2. Run: sincron-brain stats")


@app.command("set-judge")
def set_judge(
    provider: Annotated[
        str | None,
        typer.Option(
            "--provider",
            help=f"Judge provider. Supported: {', '.join(PROVIDER_API_KEY_ENV)}.",
        ),
    ] = None,
    model: Annotated[
        str | None,
        typer.Option(
            "--model",
            help="Judge model. Defaults to the canonical model for the chosen provider.",
        ),
    ] = None,
    auto: Annotated[
        bool,
        typer.Option(
            "--auto",
            help="Detect the provider from the first supported API key env var that is set.",
        ),
    ] = False,
) -> None:
    """Update the judge provider/model for an existing vault without recreating it.

    Useful when you develop with one LLM (e.g. Claude in the agent) but want
    the indexing judge to run on another provider (e.g. a cheaper or local one),
    or when you set the API key only after `connect` ran.

    Use `--auto` to pick whichever supported provider key is already exported
    in this shell — handy after a fresh install where the key only landed
    afterwards.
    """
    if auto and provider:
        console.print("[red]Use either --auto or --provider, not both.[/]")
        raise typer.Exit(1)
    if not auto and not provider:
        console.print(
            "[red]Pass --auto (detect from env) or --provider <name>.[/]\n"
            f"Supported providers: {', '.join(PROVIDER_API_KEY_ENV)}."
        )
        raise typer.Exit(1)

    if auto:
        detected = _detect_provider_from_env()
        if detected is None:
            console.print(
                "[red]No supported provider API key found in the environment.[/]\n"
                "Export one of: "
                + ", ".join(PROVIDER_API_KEY_ENV.values())
                + ", then re-run with --auto."
            )
            raise typer.Exit(1)
        provider = detected
        console.print(
            f"[green]Detected[/] {PROVIDER_API_KEY_ENV[detected]} — "
            f"using [bold]{detected}[/] as the judge provider."
        )

    if provider not in PROVIDER_API_KEY_ENV:
        console.print(
            f"[red]Unsupported provider:[/] {provider}. "
            f"Pick one of: {', '.join(PROVIDER_API_KEY_ENV)}."
        )
        raise typer.Exit(1)

    config = _load_or_die()
    _apply_judge_config(config, provider, model)
    console.print(
        f"[green]Judge updated:[/] {config.judge.provider}/{config.judge.model} "
        f"(key {config.judge.api_key_env})"
    )
    _print_judge_status(config)
    console.print()
    console.print(
        "[bold]Reminder:[/] restart your MCP client so the subprocess picks up the new judge."
    )


@app.command()
def serve() -> None:
    """Run the MCP server (stdio). Used by MCP clients."""
    from sincron_brain.server import main

    main()


@app.command("sleep-now")
def sleep_now() -> None:
    """Force the sleep/indexing job to run now."""
    from sincron_brain import judge
    from sincron_brain.sleep import run_sleep

    config = _load_or_die()
    console.print("[bold]Running sleep job...[/]")
    result = run_sleep(config, decide=judge.default_decider(config))
    console.print(
        f"[green]Done.[/] processed={result['processed']} "
        f"created={result['created']} merged={result['merged']} "
        f"({result['duration_seconds']}s)"
    )


@app.command()
def stats() -> None:
    """Print vault statistics."""
    config = _load_or_die()
    with storage.open_db(config) as conn:
        s = storage.stats(conn)

    table = Table(title=f"Vault: {config.vault_path}", show_header=False)
    table.add_column("metric", style="cyan")
    table.add_column("value", style="bold")
    table.add_row("Total memories", str(s["total"]))
    table.add_row("Distinct Major Tags", str(s["tags"]))
    table.add_row("Avg score", f"{s['avg_score']}")
    table.add_row("High-score (>=50)", str(s["high_score_count"]))
    table.add_row("Draft queue", str(len(list(config.draft_dir.glob("*.json")))))
    console.print(table)
    _print_judge_status(config)


@app.command()
def viewer(
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="HTML output path. Default: <vault>/_viewer.html."),
    ] = None,
    limit: Annotated[
        int | None,
        typer.Option("--limit", help="Maximum number of memories embedded in the HTML."),
    ] = None,
    include_content: Annotated[
        bool,
        typer.Option(
            "--include-content",
            help="Embed full memory bodies in the HTML snapshot. Use only for local inspection.",
        ),
    ] = False,
) -> None:
    """Generate a static HTML debug viewer for the current vault."""
    from sincron_brain.viewer import write_viewer

    config = _load_or_die()
    try:
        output_path = write_viewer(config, output, limit=limit, summary_only=not include_content)
    except ValueError as e:
        console.print(f"[red]{e}[/]")
        raise typer.Exit(1) from None
    console.print("[green]Viewer generated.[/]")
    console.print(f"  {output_path}")
    if limit:
        console.print(f"  Limit: {limit} memories")
    if include_content:
        console.print("  Full memory bodies embedded. Keep this HTML local.")
    else:
        console.print("  Summary-only: memory bodies omitted. Use --include-content to embed them.")


@app.command()
def benchmark(
    path: Annotated[
        Path,
        typer.Option("--path", help="Benchmark vault directory to create."),
    ],
    memories: Annotated[
        int,
        typer.Option("--memories", help="Synthetic memories to write directly."),
    ] = 1000,
    drafts: Annotated[
        int,
        typer.Option("--drafts", help="Synthetic drafts to enqueue before sleep."),
    ] = 0,
    force: Annotated[
        bool,
        typer.Option("--force", help="Replace the benchmark vault if it already exists."),
    ] = False,
    skip_viewer: Annotated[
        bool,
        typer.Option("--skip-viewer", help="Skip static viewer generation."),
    ] = False,
    skip_sleep: Annotated[
        bool,
        typer.Option("--skip-sleep", help="Do not process queued drafts with sleep."),
    ] = False,
    json_output: Annotated[
        bool,
        typer.Option("--json", help="Print benchmark result as JSON."),
    ] = False,
) -> None:
    """Run a local synthetic stress test without calling an LLM provider."""
    from sincron_brain.benchmark import run_benchmark

    try:
        result = run_benchmark(
            vault_path=path,
            memories=memories,
            drafts=drafts,
            force=force,
            render_viewer=not skip_viewer,
            run_sleep_job=not skip_sleep,
            progress=console.print,
        )
    except (FileExistsError, ValueError) as e:
        console.print(f"[red]{e}[/]")
        raise typer.Exit(1) from None

    if json_output:
        console.print_json(data=result)
        return

    console.print(f"[green]Benchmark complete.[/] Vault: {result['vault_path']}")
    console.print(
        f"  memories={result['requested_memories']} "
        f"drafts={result['requested_drafts']} "
        f"final_total={result['final_stats']['total']} "
        f"storage={result['storage']['total_mb']} MB"
    )
    if result.get("viewer_path"):
        console.print(f"  viewer={result['viewer_path']}")

    table = Table(title="Benchmark timings")
    table.add_column("step", style="cyan")
    table.add_column("seconds", justify="right", style="bold")
    table.add_column("result", overflow="fold")
    for step in result["steps"]:
        result_text = ""
        if "result_count" in step:
            result_text = f"{step['result_count']} rows"
        elif "result" in step:
            result_text = str(step["result"])
        table.add_row(step["name"], f"{step['seconds']:.4f}", result_text)
    console.print(table)

    storage_table = Table(title="Benchmark storage", show_header=False)
    storage_table.add_column("metric", style="cyan")
    storage_table.add_column("value", style="bold")
    for key, value in result["storage"].items():
        storage_table.add_row(key, str(value))
    storage_table.add_row("draft_queue", str(result["draft_queue"]))
    storage_table.add_row("reactivation_queue", str(result["reactivation_queue"]))
    console.print(storage_table)


def _load_or_die() -> VaultConfig:
    vault_value = (
        os.environ.get("SINCRON_BRAIN_VAULT")
        or _vault_path_from_project_mcp_config(Path.cwd())
        or str(_default_vault_path())
    )
    vault = Path(vault_value)
    try:
        return load_config(vault.expanduser().resolve())
    except FileNotFoundError as e:
        console.print(f"[red]{e}[/]")
        raise typer.Exit(1) from None


def _mcp_server_payload(config: VaultConfig) -> dict:
    return {
        "command": "sincron-brain",
        "args": ["serve"],
        "env": {
            "SINCRON_BRAIN_VAULT": str(config.vault_path),
        },
    }


def _write_project_mcp_config(project_path: Path, config: VaultConfig) -> Path:
    mcp_file = project_path / ".mcp.json"
    if mcp_file.exists():
        try:
            payload = json.loads(mcp_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            console.print(f"[red]Invalid JSON at {mcp_file}: {e}[/]")
            raise typer.Exit(1) from None
        if not isinstance(payload, dict):
            console.print(f"[red]{mcp_file} must contain a JSON object.[/]")
            raise typer.Exit(1)
    else:
        payload = {}

    mcp_servers = payload.setdefault("mcpServers", {})
    if not isinstance(mcp_servers, dict):
        console.print(f"[red]{mcp_file} has an invalid mcpServers value.[/]")
        raise typer.Exit(1)

    mcp_servers["sincron-brain"] = _mcp_server_payload(config)
    mcp_file.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return mcp_file


def _sync_claude_project_settings(project_path: Path) -> Path:
    """Enable project .mcp.json servers that exist, avoiding dangling Claude entries."""
    mcp_file = project_path / ".mcp.json"
    payload = json.loads(mcp_file.read_text(encoding="utf-8"))
    valid_servers = set(payload.get("mcpServers", {}).keys())

    claude_dir = project_path / ".claude"
    claude_dir.mkdir(exist_ok=True)
    settings_file = claude_dir / "settings.local.json"

    if settings_file.exists():
        try:
            settings = json.loads(settings_file.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            console.print(f"[red]Invalid JSON at {settings_file}: {e}[/]")
            raise typer.Exit(1) from None
        if not isinstance(settings, dict):
            console.print(f"[red]{settings_file} must contain a JSON object.[/]")
            raise typer.Exit(1)
    else:
        settings = {}

    enabled = settings.get("enabledMcpjsonServers", [])
    if not isinstance(enabled, list):
        enabled = []

    synced = []
    for name in enabled:
        if isinstance(name, str) and name in valid_servers and name not in synced:
            synced.append(name)
    if "sincron-brain" in valid_servers and "sincron-brain" not in synced:
        synced.append("sincron-brain")

    settings["enabledMcpjsonServers"] = synced
    settings_file.write_text(
        json.dumps(settings, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    return settings_file


MEMORY_INSTRUCTIONS_START = "<!-- sincron-brain-memory:start -->"
MEMORY_INSTRUCTIONS_END = "<!-- sincron-brain-memory:end -->"
MEMORY_INSTRUCTIONS_BLOCK = f"""{MEMORY_INSTRUCTIONS_START}
## Sincron Brain Memory

Use the `sincron-brain` MCP server as the project's long-term memory layer.

- Before answering questions that may depend on prior project/user context, inspect memory first:
  `list_major_tags()` or `search()` -> `list_tags()` -> `use_memories(ids)`.
- When using memory in a user-facing conversation, always inspect `soul` and `preferences`
  first with `list_tags("soul")` and `list_tags("preferences")`. If any identity or
  preference memory should shape the answer, fetch it through `use_memories(ids)` so it is
  injected into the working context and reactivated.
- Use `use_memories(ids)` when memory content is used in an answer. Do not use `read_memory()`
  for normal answers, because `use_memories()` queues reactivation for sleep-time scoring.
- Prefer `remember_turn(user_message, agent_response, memory_reason)` when both sides of a
  conversation turn are available. Use `remember()` for standalone durable facts, user
  preferences, project decisions, corrections, and information the user explicitly asks you
  to remember.
- Do not store secrets, API keys, tokens, passwords, or unrelated transient chatter.
- Major Tags are primary retrieval routes, not free-form facets. Use one primary Major Tag
  whenever possible. Defaults: {default_major_tag_names_csv()}.
- Common tags are noun-like retrieval labels inside a Major Tag. Before creating tags,
  inspect existing vocabulary with `list_common_tags(major_tag)` when useful. Reuse good
  existing tags, but create new snake_case singular tags when they add a useful search route.
  Avoid verbs, phrases, mini-summaries, singular/plural duplicates, and redundant synonyms.
- Create a new Major Tag only when no default category fits and the new category is generic,
  reusable across future memories, snake_case, and useful as a future search route. There is
  no separate registry command; a new Major Tag is registered when sleep indexes a memory
  with that Major Tag.
- `remember()` and `remember_turn()` only queue drafts. The sleep job indexes drafts later with
  `sleep_now()` or the configured sleep routine, compiling conversation turns into contextual
  memories rather than raw transcripts.
{MEMORY_INSTRUCTIONS_END}
"""


def _sync_agent_instruction_files(project_path: Path) -> list[Path]:
    candidates = [project_path / "AGENTS.md", project_path / "CLAUDE.md"]
    existing = [path for path in candidates if path.exists()]
    targets = existing or candidates
    synced = []

    for path in targets:
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        updated = _upsert_managed_block(current, MEMORY_INSTRUCTIONS_BLOCK)
        path.write_text(updated, encoding="utf-8")
        synced.append(path)

    return synced


def _upsert_managed_block(current: str, block: str) -> str:
    if MEMORY_INSTRUCTIONS_START in current and MEMORY_INSTRUCTIONS_END in current:
        before = current.split(MEMORY_INSTRUCTIONS_START, 1)[0].rstrip()
        after = current.split(MEMORY_INSTRUCTIONS_END, 1)[1].lstrip()
        parts = [before, block.strip(), after.rstrip()]
        return "\n\n".join(part for part in parts if part) + "\n"

    if current.strip():
        return current.rstrip() + "\n\n" + block
    return block


def _vault_path_from_project_mcp_config(project_path: Path) -> str | None:
    mcp_file = project_path / ".mcp.json"
    if not mcp_file.exists():
        return None

    try:
        payload = json.loads(mcp_file.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None

    if not isinstance(payload, dict):
        return None

    server = payload.get("mcpServers", {}).get("sincron-brain")
    if not isinstance(server, dict):
        return None

    env = server.get("env")
    if not isinstance(env, dict):
        return None

    vault_path = env.get("SINCRON_BRAIN_VAULT")
    return vault_path if isinstance(vault_path, str) and vault_path else None


def _prompt_provider() -> str:
    providers = list(PROVIDER_DEFAULT_MODEL.keys())
    console.print("[bold]Choose LLM judge provider:[/]")
    for i, p in enumerate(providers, 1):
        model = PROVIDER_DEFAULT_MODEL[p]
        env = PROVIDER_API_KEY_ENV[p]
        marker = "✓" if os.environ.get(env) else " "
        console.print(f"  {i}. [{marker}] {p:<10}  {model:<40} (uses {env})")
    choice = typer.prompt("Number", default="1")
    try:
        return providers[int(choice) - 1]
    except (ValueError, IndexError):
        return "anthropic"
